# Generated by Django 3.0.8 on 2020-08-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200814_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_Unit',
            new_name='description',
        ),
    ]
